services:
  senya:
    # network_mode: bridge
    ports:
    - mode: ingress
      target: 5000
      published: 5000
      protocol: tcp

    image: ghcr.io/stek29/senya
    build:
      context: .

    volumes:
    - ./models:/app/models:ro
    environment:
      SENYA_MODEL_PATH: models/model.npz

      GUNICORN_CMD_ARGS: >-
        --workers 1
    # command: --workers 1
